### ISSUE TITLE
TypeError in document_api.py et search_api.py 

### ISSUE THREAD

**Issue by ghost** [ian-nai/PyGallica#8]
Line 172 in document_api.py : 
file.write(soup.prettify().encode('UTF-8'))
TypeError: write() argument must be str, not bytes

Solution : change line in file.write(str(soup.prettify().encode('UTF-8')))

Same error line 32 in search_api.py

Thank you!

**Comment by ian-nai** [comment]
Thank you! Very helpful. I'll make the changes.
